### ISSUE TITLE
The virtual machine available for download is broken - Open Semantic Search Appliance (VM)

### ISSUE THREAD

**Issue by gggeek** [opensemanticsearch/open-semantic-desktop-search#1]
I am not sure if this is the good place to report bugs - but I could not find better info on the site.
Anyway: the zip file open-semantic-search-vm_15.07.15.zip contains only a .vdi file.
That is not enough to run a vbox vm: it is just the hard-disk contents.
It is arguably possible to build a full vm out of it, but then you would have to provide much more detailed instructions.
Bye
Gaetano

ps: a nitpick: the correct spelling is "machine", not "maschine"

**Comment by timglabisch** [comment]
you can create a new VM and use the vdi as existing drive. i can start the vm.

**Comment by opensemanticsearch** [comment]
This will be changed from disc format to the VMWare appliance format in next version, so the VM will be created/imported automatically on doubleclick.
