### ISSUE TITLE
Tagging and annotations

### ISSUE THREAD

**Issue by clamor** [opensemanticsearch/open-semantic-desktop-search#10]
Added entities do not get listed in the standard groups (Persons, Organizations, Locations), when adding an annotation to an indexed Document. When I add a tag, via django admin interface with the URI of the created entity the tag is listed within all groups (Tags, Persons, Organizations, Locations) of the annotation. When ticking the tag, the document is marked with the entity and the entity is listed in the correct facet in the right column. Is this behavior intended?

(using open-semantic-desktop-search_16.07.20.ova on virtualbox 5.0.26)

**Comment by opensemanticsearch** [comment]
Named Entities for automatic tagging and tags for manual tagging are yet different things / datasets.

This will be changed within the next weeks, when the Tagger webapp will be deeper integrated/consolidated with Named Entities Manager towards a thesaurus manager (SKOS).
