### ISSUE TITLE
GUI

### ISSUE THREAD

**Issue by Mandalka** [opensemanticsearch/open-semantic-desktop-search#11]
Extend GUI for indexing after booting desktop search virtual machine.
- more information than "Indexing documents", i.e. which directory/file is indexed.
- After basic indexing ask to enhance with which data enrichment plugins
- Possibility to abort

**Comment by opensemanticsearch** [comment]
More status infos and control for users and admins will be implemented more general for all packages/environments by https://github.com/opensemanticsearch/open-semantic-search/issues/155

**Comment by Mandalka** [comment]
Main search UI now with status message if still open text extraction tasks.
