### ISSUE TITLE
Highlight PDF Documents

### ISSUE THREAD

**Issue by marciopula** [opensemanticsearch/open-semantic-desktop-search#13]
Hi,

Its possible with OSDS highligh searchs on PDF's files?

I have PDF's with about 50 pages, and the idea is when i search a word get open PDF with highlight words and with next button to go to next page with searched word.

Thank You.
MR

**Comment by opensemanticsearch** [comment]
Highlighting in PDF preview was implemented end of last year.

Next button to next match/highlighting (or if PDF next page with matches) will be implemented in issue https://github.com/opensemanticsearch/open-semantic-search/issues/165
