### ISSUE TITLE
Upgrade to Debian 9

### ISSUE THREAD

**Issue by opensemanticsearch** [opensemanticsearch/open-semantic-desktop-search#14]
Upgrade to / base on new stable release Debian 9 strech

**Comment by Mandalka** [comment]
Building Virtual Box VM based on Debian 9 Stretch now automatically based on Open Semantic Search Appliance.

Todo: Migration of user/UI setup to Debian 9 Gnome Desktop version.

**Comment by Mandalka** [comment]
Gnome configuration and Firefox configuration done based on default versions on Debian 9 Stretch.
