### ISSUE TITLE
opensemanticsearch-delete

### ISSUE THREAD

**Issue by kalle44** [opensemanticsearch/open-semantic-desktop-search#16]
Hi, 

I'm using the Desktop Version as an Appliance in Virtual Box and need to delete some files from the index.
So I tried to use the command-line for this job.
 https://www.opensemanticsearch.org/doc/admin/cmd

The -delete option is not available. 
![image](https://user-images.githubusercontent.com/29337312/28308431-76cb200c-6ba6-11e7-91ed-71399fa31ae5.png)

Am I doing something wrong. Is there another way to delete files from index?

Thanks. :)

**Comment by opensemanticsearch** [comment]
The command line tool was made for an customer some weeks ago and is part of the server package since some weeks. So it will be part of the VMs next releases.

Until then you can use the REST API delete command or the native Solr API.
