### ISSUE TITLE
search package is not installed after build and run

### ISSUE THREAD

**Issue by Quyrean** [opensemanticsearch/open-semantic-desktop-search#25]
I pulled all the latest updates and built everything from scratch.  Then I started the appliance.  The first error is "bzip2 not found".  I rebooted the machine, then it started installing the vbox guest packages and other packages. 

The vm exited, then I removed the vmbox guest iso and exported the machine.  I imported the machine and started it up.  I get a "waiting for tika" window.  

It looks like tika, solr, and open semantic search is not installed on the machine.

![bzip2 not found](https://user-images.githubusercontent.com/30613311/40378556-847832c0-5db9-11e8-92de-0a92e8e6498b.PNG)

![waiting for tika](https://user-images.githubusercontent.com/30613311/40378692-ec26c878-5db9-11e8-96e0-361b4e679468.PNG)

From the vm
```
user@debian:~$ ps auxwww | grep tika
user       914  0.0  0.0   4288   732 tty1     S+   17:02   0:00 /bin/sh /usr/bin/wait_until_tika_is_up_zenity
user       917  0.0  0.0   4288  1564 tty1     S+   17:02   0:00 /bin/sh /usr/bin/wait_until_tika_is_up
user      1450  0.0  0.0  12784   996 pts/0    S+   17:04   0:00 grep tika
user@debian:~$ ls -l /etc/init.d/tika
ls: cannot access '/etc/init.d/tika': No such file or directory
user@debian:~$ 
user@debian:~$ 
user@debian:~$ ls -l /opt/solr
ls: cannot access '/opt/solr': No such file or directory
user@debian:~$ ls -l /usr/bin/etl*
ls: cannot access '/usr/bin/etl*': No such file or directory
user@debian:~$ ls -l /usr/bin/open*
-rwxr-xr-x 1 user user    213 May  1 21:46 /usr/bin/open-semantic-desktop-search
-rwxrwxr-x 1 user user    257 Jun  1  2015 /usr/bin/opensemanticsearch_index_dir_zenity
-rwxr-xr-x 1 user user    255 May  1 21:46 /usr/bin/opensemanticsearch_index_dir_zenity_foreground
-rwxr-xr-x 1 root root 651880 Mar 29 10:51 /usr/bin/openssl
user@debian:~$ su
root@debian:/home/user# find / -name "open-semantic-search*"
^C
root@debian:/home/user# ^C
root@debian:/home/user# find / -name "open-semantic-search*" -print
find: ‘/run/user/1000/gvfs’: Permission denied
/var/lib/dpkg/info/open-semantic-search-apps.conffiles
/var/lib/dpkg/info/open-semantic-search-apps.list
/var/lib/dpkg/info/open-semantic-search-apps.md5sums
/var/lib/dpkg/info/open-semantic-search-apps.postinst
/etc/cron.d/open-semantic-search
root@debian:/home/user# 
```

here is my build script

[build-desktop.txt](https://github.com/opensemanticsearch/open-semantic-desktop-search/files/2027807/build-desktop.txt)

Any idea what is going wrong?  Thanks.

**Comment by Mandalka** [comment]
Closing old issue.

Modernized build based on Ansible playbook in https://github.com/opensemanticsearch/open-semantic-search/tree/master/src/open-semantic-desktop-search
