### ISSUE TITLE
flower doesn't start automatically

### ISSUE THREAD

**Issue by DieGoldeneEnte** [opensemanticsearch/open-semantic-desktop-search#29]
The last commit ("Add Swapfile") removes the file /etc/rc.local which is used to start flower on start up.
The rc.local file gets copied to /etc/ in the install.sh file line 116:
`cp -a /usr/src/customize/includes.chroot/* /`
and is removed in line 136 of the same file:
`rm /etc/rc.local`

**Comment by Mandalka** [comment]
Thanx for buf report. Is not removed anymore.

Todo: Start flower (using own system user) by systemd config instead of rc.local

**Comment by Mandalka** [comment]
Flower starting again in newest release of Desktop Search VM (now based on Debian 10).

Yet by rc.local, which in a user VM without external access is not critical.

**Comment by Mandalka** [comment]
For upgrade to Debian 10.7, after this quick and dirty hack led to hanging poweroff / reboot start of flower now as systemd service (running as own user flower), so last todo here done.
