### ISSUE TITLE
Upgrade to Debian 10

### ISSUE THREAD

**Issue by opensemanticsearch** [opensemanticsearch/open-semantic-desktop-search#30]
Upgrade to new Debian release

**Comment by Mandalka** [comment]
Removed installation of Tesseract from backports, since Tesseract 4 now in main package repository of new Debian release.

**Comment by Mandalka** [comment]
Fixed some Apache/Django issues based on newer versions of libraries/dependencies in https://github.com/opensemanticsearch/open-semantic-search-apps/issues/57

**Comment by Mandalka** [comment]
The base Debian package of the [search engine now runs on Debian 10](https://github.com/opensemanticsearch/open-semantic-search/issues/195).

A run on Debian 9 of vmdebootstrap of Debian stable (10) yet builds a VM with wrong network settings.

Will try after upgrade the development system to Debian 10, if new version of vmdebootstrap works or which new / changed packages or configs to add in the VM.

**Comment by Mandalka** [comment]
Network settings in VM after VMdebootstrap are ok out of the box.

Problem was (if not additionally some things running better after upgraded to vmdebootstrap of Debian 10 in build system) / is that in Debian 10 rc.local (temporary misused for installations in VM) starts before network is up.

**Comment by Mandalka** [comment]
Install script now waits until network available in VM.
