### ISSUE TITLE
Screen size / resolution

### ISSUE THREAD

**Issue by opensemanticsearch** [opensemanticsearch/open-semantic-desktop-search#34]
If building with current VirtualBox and Debian the screen size is set fix to 800X600px (can be set to biger but fixed size in Gnome screen settings inside the virtual Debian environment), instead of dynamic to current size of the Virtual Box window.

**Comment by Mandalka** [comment]
Seems to Work again, if using Virtual Box setting of "Graphics controller" of the VM to VMSVGA instead of VBoxVGA

**Comment by Mandalka** [comment]
Now explicit set by VBoxManage parameter in build script.
