### ISSUE TITLE
Rich PDF preview fails

### ISSUE THREAD

**Issue by opensemanticsearch** [opensemanticsearch/open-semantic-desktop-search#35]
Rich PDF preview in tab content fails (so we can see only extracted text in tab plain text) because current relase of Firefox after upgrade the old profile (without handlers.js) is set (accessable by standard Firefox settings UI/Menu, so current users can change the setting very easy) to ask what to do with PDF instead of directly preview them in Firefox automatically, so we have to change this setting.

**Comment by Mandalka** [comment]
Seems to be managed by handlers.json in Mozilla Firefox profile dir:

"mimeTypes":{"application/pdf":{"action":2,"extensions":["pdf"],"ask":true}}

vs

"mimeTypes":{"application/pdf":{"action":3,"extensions":["pdf"]}}

**Comment by Mandalka** [comment]
Sine other issues with upgrading from this very old profile, not there is a fresh Firefox profile solving this issues (internal pdf viewer was set as default by Firefox).
