### ISSUE TITLE
Upgrade to Debian 10.6

### ISSUE THREAD

**Issue by opensemanticsearch** [opensemanticsearch/open-semantic-desktop-search#36]
Fix breaking changes by / upgrade to Debian 10.6

**Comment by Mandalka** [comment]
Problem why Open Semantic ETL fails: "pip3 install flower" installs newer/incompatible releases of dependencies of f.e. Celery now, (maybe before so no python packages yet installed by apt or without pinning newer releases dependent) the dependencies are resolved by Debian packages by apt.

**Comment by Mandalka** [comment]
Problem why login fails: Error on useradd because missing group because groupadd before failed because group tesseract_cache got gid 1000.
