### ISSUE TITLE
Upgrade to Debian 10.7

### ISSUE THREAD

**Issue by opensemanticsearch** [opensemanticsearch/open-semantic-desktop-search#37]
http://ftp.debian.org/debian/dists/buster/ChangeLog

**Comment by Mandalka** [comment]
Most things seem to run now after f.e. pip upgrade to be able to install new SpaCy release.

Todo:

- no (virtual) power off of the VM or automatic reset if restarting.
-Last message: "Stopped RabbitMQ", after that nothing happens until manual / hard VM power off or reset

- flower does not show  ETL tasks.

**Comment by Mandalka** [comment]
The reboot / (virtual) poweroff problem seems to be the flower process which was started in /etc/rc.local

**Comment by Mandalka** [comment]
Flower is removed from rc.local now running as own systemd service and as own user.

After that Open Semantic Desktop Search seems to work on new Debian 10.7 as VM image OS.
