### ISSUE TITLE
Source code

### ISSUE THREAD

**Issue by xchen97** [opensemanticsearch/open-semantic-desktop-search#5]
Hi,

Is the source code still available? If so, please provide a link to it.

Thanks.

**Comment by csyao** [comment]
+1

**Comment by opensemanticsearch** [comment]
None of the releases are only binaries (only exception: The Tika & Solr Java binaries, which are the official standard binaries from the Apache project and all codes are available there).

Our Python/PHP/Shell scripts and all configs included in the VM are not compiled and so a release is a release of the source code, too.

The .deb packages include declarations of the dependencies.

In the next days (after a customers new extensions are included) all codes of all modules and the VM build script will be available on Github, too.
