### ISSUE TITLE
Problem downloading VM

### ISSUE THREAD

**Issue by bmoraillon** [opensemanticsearch/open-semantic-desktop-search#6]
Hi,
i can't download the last release of open semantic search server vm. File seams to be corrupted. I get a CRC check error when i unzip it.
Also, the Paris Mirror seams to be broken.

Thanks,
Best regards.

**Comment by andymnc** [comment]
all the download links here http://www.opensemanticsearch.org/download/
are broken

**Comment by opensemanticsearch** [comment]
The new release of Open Semantic Desktop Search is available on the main server, so the link works now.

Mirror servers will follow next days.

The new Open Semantic Search server VM will follow next week.

**Comment by markedphillips** [comment]
The links seem to be down right now too.
