### ISSUE TITLE
Admin rights (sudo) for installing additional software packages

### ISSUE THREAD

**Issue by opensemanticsearch** [opensemanticsearch/open-semantic-desktop-search#8]
Config admin rights within the GUI by sudo for installing additional packages or change config files without need to change to the systems root console by press CTRL-Right and F2 at once (To get back logout with exit and press ALT-F1).

**Comment by Mandalka** [comment]
No need for configuration of sudo any more, since after upgrade to Debian 9 you can use the command su on command line in the terminal within the Gnome UI to get root, which was added to documentation.
